### ISSUE TITLE
Network Learning Problem (Answer Converges to 0.5)

### ISSUE THREAD

**Issue by nirex0** [giladfrid009/GNet#3]
# The Problem
The network doesn't seem to be able to learn XOR (Only thing tested so far) as the answer converges to "0.5" with an architecture of [2, 25, 25, 1] All Dense layers using Hyperbolic Tangent as the activation function.

# The Solution
There are certain things that are possible to be responsible for this issue.
The first thing that came to mind is the distribution for weight and bias initialization.

```W``` should be initialized using Gaussian (Normal) Distribution of values between ```-0.5``` and ```0.5``` with a very narrow dispersion calculated using a constant scale like ```0.01```.

```B``` should be initialized to 0 across all layers so that it can tune itself better later on in the training process.

### So in short
This should be how W and B are initialized.
```C#
W = Gaussian(-0.5, 0.5) * 0.01;
B = 0; 
```
### Code used

```C#
Network net = new Network
(
    new Layers.Dense(new Shape(2), new Tanh(), new Normal()),
    new Layers.Dense(new Shape(25), new Tanh(), new Normal()),
    new Layers.Dense(new Shape(25), new Tanh(), new Normal()),
    new Layers.Dense(new Shape(1), new Tanh(), new Normal())
);

net.Train(LogicGates.XOR, new MSE(), new Default(0.033), 1, 10000, 0.01, 
    LogicGates.XOR, new Accuracy());

net.Forward(new ImmutableShapedArray<double>(new Shape(2), 0, 0)).ForEach(Console.WriteLine);
net.Forward(new ImmutableShapedArray<double>(new Shape(2), 0, 1)).ForEach(Console.WriteLine);
net.Forward(new ImmutableShapedArray<double>(new Shape(2), 1, 0)).ForEach(Console.WriteLine);
net.Forward(new ImmutableShapedArray<double>(new Shape(2), 1, 1)).ForEach(Console.WriteLine);
```

**Comment by giladfrid009** [comment]
Usually, simple problems as XOR doesn't require such long layers with 25 neurons. the longer the layer, the harder for the network is to train. a Sufficient structure for the XOR problem is [2,2,1].

Regarding W initialization, I added the option in commit d19e1226e4ed006d271153c936857f96a24fc5c6 to set custom SD and mean for the Noraml initializer.
Default B initializer is zero, yet it can be changed.

Also, losses can be used as metrics (ILoss : IMetric), so MSE or any other loss will show an incremental decrease in the error as the training progresses.
